### ISSUE TITLE
v3 ドキュメントの翻訳

### ISSUE THREAD

**Issue by potato4d** [vuejs-jp/ja.vuejs.org#1]
**今の全体進捗は[こちら](https://github.com/vuejs-jp/ja.vuejs.org/projects/1)**

## About

これは Vue.js v3 のドキュメントを翻訳するための Epic Issue です！
翻訳全体に関するコミュニケーションは、この Issue と、適宜 Vue.js JP Slack を利用して行っていくこととします。

今回のは **めちゃくちゃ膨大** です。
一つ一つも重いページが多いので、一人一つのページを担当するくらいの気持ちでやっていきましょう！

## Translation Flow

ひとまず以下をベースとします！

1. 翻訳希望のセクションについて、該当の Issue またはここで @potato4d  や @vuejs-jp/contributers に mention してください
2. アサインをわかりやすくするため、GitHub の Assignees の設定用にレポジトリの Read 権限を付与します。
3. 付与されたまたはこの Issue や担当 Issue で名前が設定された人は、1~2週間を目安に翻訳してください。
4. 翻訳が出来上がったら、 Pull Request を発行し、該当のセクションについて `resolve #n` の形式で Issue 番号を指定した Pull Request を送ってください。
5. ~1週間程度でレビュアーがレビューするので、適宜打ち返してください。

### 翻訳が滞っている場合

2週間立っても翻訳が進んでいないものは、適宜タスクを巻き取りたい人が声を上げてください！その人に一旦担当を差し替えます。

## Translate Sections

:tada: Almost done! 🎉 

<details>
  <summary>Open Detail</summary>

### Essentials

- [x] Installation #2 
  - Ref: [guide/installation.html](https://v3.vuejs.org/guide/installation.html)|
- [x] Introduction #3 
  - Ref: [guide/introduction.html](https://v3.vuejs.org/guide/introduction.html)|
- [x] The Application Instance #4 
  - Ref: [guide/instance.html](https://v3.vuejs.org/guide/instance.html)|
- [x] Template Syntax #5 
  - Ref: [guide/template-syntax.html](https://v3.vuejs.org/guide/template-syntax.html)|
- [x] Computed Properties and Watchers #49 
  - Ref: [guide/computed.html](https://v3.vuejs.org/guide/computed.html)|
- [x] Class and Style Bindings #6  
  - Ref: [guide/class-and-style.html](https://v3.vuejs.org/guide/class-and-style.html)|
- [x] Conditional Rendering #7 
  - Ref: [guide/conditional.html](https://v3.vuejs.org/guide/conditional.html)|
- [x] List Rendering #8 
  - Ref: [guide/list.html](https://v3.vuejs.org/guide/list.html)|
- [x] Event Handling #9 
  - Ref: [guide/events.html](https://v3.vuejs.org/guide/events.html)|
- [x] Form Input Bindings #10 
  - Ref: [guide/forms.html](https://v3.vuejs.org/guide/forms.html)|
- [x] Components Basics #11 
  - Ref: [guide/component-basics.html](https://v3.vuejs.org/guide/component-basics.html)|

### Components In-Depth

- [x] Component Registration #12 
  - Ref: [guide/component-registration.html](https://v3.vuejs.org/guide/component-registration.html)|
- [x] Props  #13 
  - Ref: [guide/component-props.html](https://v3.vuejs.org/guide/component-props.html)|
- [x] Non-Prop Attributes #14 
  - Ref: [guide/component-attrs.html](https://v3.vuejs.org/guide/component-attrs.html)|
- [x] Custom Events #15 
  - Ref: [guide/component-custom-events.html](https://v3.vuejs.org/guide/component-custom-events.html)|
- [x] Slots #16 
  - Ref: [guide/component-slots.html](https://v3.vuejs.org/guide/component-slots.html)|
- [x] Provide / inject #17 
  - Ref: [guide/component-provide-inject.html](https://v3.vuejs.org/guide/component-provide-inject.html)|
- [x] Dynamic & Async Components #18 
  - Ref: [guide/component-dynamic-async.html](https://v3.vuejs.org/guide/component-dynamic-async.html)|
- [x] Template refs #19 
  - Ref: [guide/component-template-refs.html](https://v3.vuejs.org/guide/component-template-refs.html)|
- [x] Handling Edge Cases #20 
  - Ref: [guide/component-edge-cases.html](https://v3.vuejs.org/guide/component-edge-cases.html)|

### Transitions & Animation

- [x] Overview #21 
  - Ref: [guide/transitions-overview.html](https://v3.vuejs.org/guide/transitions-overview.html)|
- [x] Enter & Leave Transitions #22 
  - Ref: [guide/transitions-enterleave.html](https://v3.vuejs.org/guide/transitions-enterleave.html)|
- [ ] List Transitions #23 
  - Ref: [guide/transitions-list.html](https://v3.vuejs.org/guide/transitions-list.html)|
- [x] State Transitions #24 
  - Ref: [guide/transitions-state.html](https://v3.vuejs.org/guide/transitions-state.html)|

### Reusability & Composition

- [x] Mixins #25 
  - Ref: [guide/mixins.html](https://v3.vuejs.org/guide/mixins.html)|
- [x] Custom Directives #26 
  - Ref: [guide/custom-directive.html](https://v3.vuejs.org/guide/custom-directive.html)|
- [x] Teleport #27  
  - Ref: [guide/teleport.html](https://v3.vuejs.org/guide/teleport.html)|
- [x] Render Functions #28 
  - Ref: [guide/render-function.html](https://v3.vuejs.org/guide/render-function.html)|
- [x] Plugins #29 
  - Ref: [guide/plugins.html](https://v3.vuejs.org/guide/plugins.html)|

#### Reactivity

- [x] Reactivity in Depth #30 
  - Ref: [guide/reactivity.html](https://v3.vuejs.org/guide/reactivity.html)|
- [x] Reactivity Fundamentals  #31 
  - Ref: [guide/reactivity-fundamentals.html](https://v3.vuejs.org/guide/reactivity-fundamentals.html)|

#### Compotion API

- [x] Compotion API > Introduction #32 
  - Ref: [guide/composition-api-introduction.html](https://v3.vuejs.org/guide/composition-api-introduction.html)|
- [x] Compotion API > Setup #33 
  - Ref: [guide/composition-api-setup.html](https://v3.vuejs.org/guide/composition-api-setup.html)|
- [x] Compotion API > Lifecycle Hooks #34 
  - Ref: [guide/composition-api-lifecycle-hooks.html](https://v3.vuejs.org/guide/composition-api-lifecycle-hooks.html)|
- [x] Compotion API > Provide / Inject #35 
  - Ref: [guide/composition-api-provide-inject.html](https://v3.vuejs.org/guide/composition-api-provide-inject.html)|
- [x] Compotion API > Template Refs #36 
  - Ref: [guide/composition-api-template-refs.html](https://v3.vuejs.org/guide/composition-api-template-refs.html)|

#### Render Mechanisms

- [x] Rendering Mechanisms and Optimizations #37 
  - Ref: [guide/optimizations.html](https://v3.vuejs.org/guide/optimizations.html)|
- [x] Change Detection Caveats in Vue 2 #38 
  - Ref: [guide/change-detection.html](https://v3.vuejs.org/guide/change-detection.html)|

### Tooling

- [x] Single File Components #39 
  - Ref: [guide/single-file-component.html](https://v3.vuejs.org/guide/single-file-component.html)|
- [x] Testing #40 
  - Ref: [guide/testing.html](https://v3.vuejs.org/guide/testing.html)|
- [x] TypeScript Support #41 
  - Ref: [guide/typescript-support.html](https://v3.vuejs.org/guide/typescript-support.html)|

### Scaling Up

- [x] Routing #42
  - Ref: [guide/routing.html](https://v3.vuejs.org/guide/routing.html)|
- [x] State Management #43 
  - Ref: [guide/state-management.html](https://v3.vuejs.org/guide/state-management.html)|
- [x] Server-Side Rendering #44 
  - Ref: [guide/ssr.html](https://v3.vuejs.org/guide/ssr.html)|

### Accessibility

- [x] Basic #45 
  - Ref: [guide/a11y-basics.html](https://v3.vuejs.org/guide/a11y-basics.html)|
- [x] Semantics #46 
  - Ref: [guide/a11y-semantics.html](https://v3.vuejs.org/guide/a11y-semantics.html)|
- [x] Standards #47 
  - Ref: [guide/a11y-standards.html](https://v3.vuejs.org/guide/a11y-standards.html)|
- [x] Resources #48 
  - Ref: [guide/a11y-resources.html](https://v3.vuejs.org/guide/a11y-resources.html)|

</details>

### Migration Guide

- [x] Introduction #106 
- [ ] v-for Array Refs #107
- [x] Async Components #108
- [x] Attribute Coercion Behavior #109
- [x] Custom Directives #110
- [x] Custom Elements Interop #111
- [x] Data Option #112
- [x] Events API #113
- [x] Filters #114
- [x] Fragments #115
- [x] Functional Components #116
- [x] Global API #117
- [x] Global API Treeshaking #118
- [x] Inline Template Attribute #119
- [x] `key` attribute #120
- [x] KeyCode Modifiers #121
- [x] Props Default Function `this` Access #122
- [x] Render Function API #123
- [x]  Slots Unification #124
- [x] Transition Class Change #125
- [x] v-model #126
- [x] v-if vs. v-for Precedence #127
- [x] v-bind Merge Behavior #128

### Contribute to the Docs

- [x] Vue Docs Writing Guide #129
- [x] Documentation Style Guide #130
- [x] Translations #131

**Comment by potato4d** [comment]
とりあえず pr-triage 入れて全部 Issue 立てるまではやった

**Comment by t0yohei** [comment]
@potato4d 
ここにコメントすれば良さそうですかね。 #30 の issue を担当したいです。
https://github.com/vuejs-jp/ja.vuejs.org/issues/30

**Comment by RyoNkmr** [comment]
@potato4d 
お疲れ様です。早速ですが、 Essentials > Installation の翻訳 #2 挙手します🙋‍♂️

**Comment by potato4d** [comment]
@t0yohei @RyoNkmr 

はい！大丈夫です！個別 Issue でも問題ありませんー！invite 飛ばしました 🙏 
ここ毎回書くとすごい範囲に通知が行く Issue になりそうなので、今後は Reaction で対応していくかもですー

**Comment by konu96** [comment]
@potato4d 
#36 の翻訳をやりたいです

**Comment by bobstrange** [comment]
@potato4d 

> Additional Translate Sections
> Migration from Vue 2.x
> Contribute to the Docs

Migrationの部分かなりボリュームが多いので、ページ毎にIssueを立てていただいた方が良さそうです :bow:
Contribute to the Docsも3ページほどあるみたいです。

**Comment by potato4d** [comment]
@bobstrange 

あ、把握済みです。
Addtional Translation としてあるのは、ひとまず優先的にドキュメントとして必要なものを揃えたいからですー！
Open しているものから協力いただけますと幸いです……！

**Comment by mascii** [comment]
@potato4d Advanced Guides > Compotion API > Reactivity Fundamentals #31 の issue を担当したいです。

**Comment by bake0937** [comment]
@potato4d  Scaling Up > Routing の翻訳 #42 の Issueを担当したいです．

**Comment by nandenjin** [comment]
@potato4d Essentials -> The Application Instance #4 担当したいです:raising_hand:

**Comment by n-makoto** [comment]
@potato4d Components In-Depth > Props の翻訳 #13 のissueを担当したいです！よろしくお願いします！

**Comment by takumiz19** [comment]
@potato4d Tooling > Single File Components の翻訳 #39 のIssueを担当したいです！！

**Comment by krabben16** [comment]
@potato4d  Scaling Up >  Server-Side Rendering の翻訳 #44 のIssueを担当したいです！

**Comment by saitoeku3** [comment]
@potato4d Compotion API > Introduction #32 を担当したいです！

**Comment by resessh** [comment]
@potato4d  Components In-Depth > Dynamic & Async Components の翻訳 #18 やりたいです 🙏

**Comment by YukiOta** [comment]
@potato4d Scaling Up > State Management の翻訳 #43 を担当したいです！

**Comment by fussy113** [comment]
@potato4d Components In-Depth > Custom Events の翻訳 #15を担当したいです！

**Comment by Nag729** [comment]
@potato4d Reusability & Composition > Mixins の翻訳 #25 を担当したいです！

**Comment by NozomuIkuta** [comment]
@potato4d TypeScript Support #41 を担当したいです。

**Comment by yamanoku** [comment]
@potato4d Accessibility Basic #45 の翻訳担当します！

**Comment by ebarakazuhiro** [comment]
@potato4d Components In-Depthの #20 の翻訳担当やります。

**Comment by DuGlaser** [comment]
@potato4d Accessibility > Resourcesの #48 を担当したいです。

**Comment by Pittan** [comment]
@potato4d san
https://github.com/vuejs-jp/ja.vuejs.org/issues/27 お手伝いさせてください 🙋

**Comment by HomMarkHunt** [comment]
@potato4d 
Components In-Depth > Component Registration #12 の翻訳お手伝いさせていただきたいです！

**Comment by sunecosuri** [comment]
@potato4d Accessibility -> Semantics #46　手伝わせてください〜

**Comment by yh1224** [comment]
@potato4d 
Essentials > Introduction #3 の翻訳をお手伝いさせていただけますでしょうか？

**Comment by fuku710** [comment]
@potato4d すみません #33 ですでに手を挙げている人に気づかなかったので、Components In-Depth > Non-Prop Attributes の翻訳 #14 の翻訳をやってもいいですか？

**Comment by YopiNoji** [comment]
@potato4d 
Tooling > Testing #40 の翻訳担当します！

**Comment by h6ah4i** [comment]
@potato4d 
🙋‍♂️ Change Detection Caveats in Vue 2 #38
の翻訳担当したいです…！

**Comment by takanakahiko** [comment]
@potato4d 
Transitions & Animation > Overview の翻訳 #21 を担当させてください。

**Comment by ryoAccount** [comment]
@potato4d 

https://github.com/vuejs-jp/ja.vuejs.org/issues/47
担当をいただいても良いでしょうか？

**Comment by kawamataryo** [comment]
@potato4d 
Compotion API > Provide / Inject #35 の翻訳を担当したいです

**Comment by kawamataryo** [comment]
@potato4d 

Testing #40 を担当したいです

**Comment by y-temp4** [comment]
@potato4d 

Rendering Mechanisms and Optimizations #37 を担当したいです🙌

**Comment by gsidendo** [comment]
@potato4d 
こちらを担当したいです
Slots #16

**Comment by daisuke-endo** [comment]
@potato4d
こちらを担当したいです
Slots #16

**Comment by an-0305** [comment]
@potato4d 
こちらを担当したいです
#29

**Comment by potato4d** [comment]
みなさんありがとうございます！

#### ❤️  をつけている方へ

Assigned になっているので、該当セクションの翻訳をお願いいたします。
また、併せてレポジトリの Outside Collaborator に招待しています。これによって Issue に明示的に Assign をつけることができるようになるので、承諾と、もし可能なら該当Issueへの自分のアサインをお願いいたします。

#### :eyes: を付けている方へ

申し訳ないのですが被りの処理で順番が前後してしまっているものがあるので、他のセクションを協力いただけますと幸いです 🙇‍♂️

**Comment by HikaruEgashira** [comment]
@potato4d #26 を担当したいです🙋

**Comment by daisuke-endo** [comment]
@potato4d 
#22を担当できますか?

**Comment by potato4d** [comment]
ひとまず現在の全てのセクションについて、翻訳アサインが決定しました！ 🎉 
レビューのリソースと品質確保のため、ひとまずここで翻訳募集自体は締め切ります 📝 
また現時点でのものが全てできた段階で、 Additional Translation にもうつっていきたいと思いますので、その時はみなさまよろしくお願いいたします。

✁✁✁✁✁✁✁✁✁✁

**Comment by Masa-Shin** [comment]
@potato4d 
以下のような箇所の訳し方って決まっていますか？
（ページ横断的に出てくるので、訳すかどうかも含め統一しておいた方が良いかと思いまして）

<img width="142" alt="スクリーンショット 2020-09-19 13 05 23" src="https://user-images.githubusercontent.com/34234442/93658785-b1d90c80-fa79-11ea-8160-24a7ad7077f6.png">
<img width="132" alt="スクリーンショット 2020-09-19 13 13 17" src="https://user-images.githubusercontent.com/34234442/93658813-e64cc880-fa79-11ea-8e09-1d2babad89ca.png">
<img width="138" alt="スクリーンショット 2020-09-19 13 06 16" src="https://user-images.githubusercontent.com/34234442/93658788-b56c9380-fa79-11ea-9898-4307db53488c.png">
<img width="155" alt="スクリーンショット 2020-09-19 13 06 24" src="https://user-images.githubusercontent.com/34234442/93658790-b56c9380-fa79-11ea-83ac-b8a3eab251b5.png">
<img width="151" alt="スクリーンショット 2020-09-19 13 09 08" src="https://user-images.githubusercontent.com/34234442/93658792-b69dc080-fa79-11ea-94d4-d50f6c0fb389.png">
<img width="98" alt="スクリーンショット 2020-09-19 13 16 03" src="https://user-images.githubusercontent.com/34234442/93658864-6c690f00-fa7a-11ea-9908-6db18f2d3c56.png">

**Comment by NozomuIkuta** [comment]
@potato4d 

> また、併せてレポジトリの Outside Collaborator に招待しています。これによって Issue に明示的に Assign をつけることができるようになるので、承諾と、もし可能なら該当Issueへの自分のアサインをお願いいたします。

こちら、AssigneeのUIが操作できないので、まだ招待されていないかもしれません。ご確認お願いできますか. 🙏 
（もしかして、自分のPRのCIが通らなかったのはこれのせいですか。PR自体はすでにマージ済みですが）

**Comment by kazupon** [comment]
@Masa-Shin 
翻訳しない方向でお願いします！

**Comment by kazupon** [comment]
@NozomuIkuta 
Outside Collaborator に招待しておきました。

**Comment by Masa-Shin** [comment]
> こちら、AssigneeのUIが操作できないので、まだ招待されていないかもしれません。

@kazupon
お手数をおかけし申し訳ありませんが、 こちらよろしければ私もお願いいたします。

**Comment by YukiOta** [comment]
@kazupon 
重ねてで恐縮ですが、自分も来ていないようだったので招待いただけると幸いです。

**Comment by kazupon** [comment]
@Masa-Shin 
確認したのですが、Outside collaborator として追加されているようです。 🤔 
![image](https://user-images.githubusercontent.com/72989/93781427-561ea700-fc64-11ea-89a3-3485c704ab6f.png)

**Comment by kazupon** [comment]
@YukiOta 
先程招待しました！

**Comment by Masa-Shin** [comment]
@kazupon 
お手数をおかけしすみません、確かにそうでした。CIは別の原因みたいですね。

**Comment by t0yohei** [comment]
@potato4d @egurinko 
翻訳準備ありがとうございます！
https://github.com/vuejs-jp/ja.vuejs.org/issues/106
を担当したいです！よろしくお願いします。

**Comment by konu96** [comment]
@potato4d @egurinko 
こちら翻訳したいです.

https://github.com/vuejs-jp/ja.vuejs.org/issues/127

**Comment by takumiz19** [comment]
@potato4d @egurinko
こちら翻訳させてください！
#126

**Comment by ryoAccount** [comment]
@potato4d @egurinko 
こちらを翻訳したいです。
https://github.com/vuejs-jp/ja.vuejs.org/issues/120

**Comment by Katakuranatsumi** [comment]
@potato4d @egurinko 
ご準備ありがとうございましたmm
#114を翻訳させていただきたいですmm

**Comment by yuta17** [comment]
@potato4d @egurinko 
#115 こちらを翻訳したいです。

**Comment by n-makoto** [comment]
@potato4d @egurinko
#113 の翻訳をしたいです！Assignお願いします:pray:

**Comment by potato4d** [comment]
みなさんありがとうございます！

 ❤️ がついている方、アサインいたしました！よろしくお願いいたします！
:eyes: がついている方、被りが発生したので、別のセクションに取り組んでいただけますと幸いです 🙇 

引き続き、よろしくお願いいたします！

**Comment by resessh** [comment]
@potato4d @egurinko 
#123 こちら翻訳したいです 🙏

**Comment by jay-es** [comment]
@potato4d @egurinko
`Migration Guide > Functional Components の翻訳` #116
を担当させていただきたいです。
よろしくお願いします。

**Comment by RyoNkmr** [comment]
@potato4d @egurinko 
空いてたらこれやります。よろしくおねがいします
https://github.com/vuejs-jp/ja.vuejs.org/issues/118

**Comment by daisuke-endo** [comment]
@potato4d @egurinko
Migration Guide > Transition Class Change の翻訳 #125
こちら担当できますか？

**Comment by ryoasu** [comment]
@potato4d @egurinko 
Migration Guide > Custom Directives の翻訳 #110
こちら担当させて欲しいです 🙏

**Comment by YosukeCSato** [comment]
@potato4d @egurinko 
https://github.com/vuejs-jp/ja.vuejs.org/issues/122
こちらの翻訳の担当をしたいです。よろしくお願いします。

**Comment by n-makoto** [comment]
@potato4d @egurinko
#109 の翻訳をさせて頂きたいです！🙏

**Comment by kawamataryo** [comment]
@potato4d 
#111 の翻訳を担当したいです!

**Comment by Katakuranatsumi** [comment]
@potato4d  @egurinko 
#130 の翻訳をさせていただきたいです🙏
