### ISSUE TITLE
v3 ドキュメントの翻訳_3部 スターダストクルセイダース

### ISSUE THREAD

**Issue by naokie** [vuejs-jp/ja.vuejs.org#288]
個人的に興味の赴くまま、順不同でやってきたため、進捗状況の可視化だけしておきます。

どれも原文の master から遅れてしまっているため「この翻訳やります！」という方いたら、コメントいただけると助かります 🙏🏼 

#150 によると 2020/09/15
https://github.com/vuejs-jp/ja.vuejs.org/commit/032c9d5a3eeab8f89648f96b23cc3d7ee93c7407 
このコミットから原文との乖離がはじまっていますが、
ガイドの目安としては、だいたい 2020/10/03 以降のコミットから徐々に遅れてきています。

## 基本的な使い方
- [x] インストール #271
- [x] はじめに #272
- [x] アプリケーションとコンポーネントのインスタンス #273
- [x] テンプレート構文 #274
- [x] データプロパティとメソッド #268
- [x] 算出プロパティとウォッチャ #279
- [x] クラスとスタイルのバインディング
- [x] 条件付きレンダリング #278
- [x] リストレンダリング #275
- [x] イベントハンドリング #276
- [x] フォーム入力バインディング #277
- [x] コンポーネントの基本 #281
## コンポーネントの詳細
- [x] コンポーネントの登録
- [x] プロパティ #298
- [x] プロパティでない属性 #299 
- [x] カスタムイベント #300 
- [x] スロット #293
- [x] Provide / inject #301 
- [x] 動的 & 非同期コンポーネント #302 
- [x] テンプレート参照について
- [x] 特別な問題に対処する #303
## トランジションとアニメーション
- [x] 概要 by @Katakuranatsumi #312  
- [x] Enter & Leave トランジション by @Katakuranatsumi #307 
- [x] リストのトランジション #318 
- [x] 状態のトランジション
## 再利用と構成
- Composition API 
  - [x] はじめに #282
  - [x] セットアップ #283
  - [x] ライフサイクルフック #287
  - [x] Provide / Inject #286
  - [x] テンプレート参照 #285
- [x] ミックスイン #290 
- [x] カスタムディレクティブ #291
- [x] Teleport #292
- [x] Render 関数 #308 
- [x] プラグイン #311 
## 高度な使い方
- リアクティビティ 
  - [x] リアクティブの探求 #314 
  - [x] リアクティブの基礎 #313 
  - [x] 算出プロパティとウォッチ #315 
- [x] レンダリングのメカニズムと最適化 #316 
- [x] Vue 2 での変更検出の注意事項 #317 
## ツール
- [x] 単一ファイルコンポーネント #309 
- [x] テスト #310 
- [x] TypeScript のサポート #297
- [x] モバイル #269
- [x] 実運用への展開 #270
## スケールアップ
- [x] ルーティング #305 
- [x] 状態管理 #306 
- [x] サーバサイドレンダリング #319 
## アクセシビリティ
- [x] 基礎 #294
- [x] セマンティクス #295
- [x] 標準
- [x] リソース #296

---

## Server-Side Rendering Guide
- [x] Introduction #321 
- [x] Getting Started #322 
- [x] Writing Universal Code #323 
- [x] Source Code Structure #325 
- [x] Build Configuration #349 
- [x] Server Configuration #351 
- [x] Routing and Code-Splitting #352 
- [x] Client Side Hydration #355

**Comment by Katakuranatsumi** [comment]
@naokie 
もしまだ着手されていなければ、Enter & Leave トランジション の翻訳をさせていただけたらと思います🙏

**Comment by naokie** [comment]
@Katakuranatsumi 
ありがとうございます！ぜひ、よろしくお願いします 🙏🏼

**Comment by Katakuranatsumi** [comment]
@naokie 
先日はレビューありがとうございましたmm
またもしまだ着手されていなければ、トランジションとアニメーションの概要の作業をさせていただけたらと思います🙏

**Comment by naokie** [comment]
はい、よろしくお願いします!!

**Comment by naokie** [comment]
エッセンシャルガイドの翻訳はひと通りすべて完了したため、クローズします。
以降の原文への追従は che-tsumi-next であがってくる issues ベースで行います。
