### ISSUE TITLE
3.2 アップデートの翻訳

### ISSUE THREAD

**Issue by naokie** [vuejs-jp/ja.vuejs.org#477]
3.2 で追加されたドキュメントの翻訳をやっていただける方を募集しています！！
コメントいただけたら、Issue を作成してアサインします。

* [x] #491
* [x] [SFC `<script setup>`](https://v3.ja.vuejs.org/api/sfc-script-setup.html) #603
* [x] #483
* [x] [SFC Style Features](https://v3.ja.vuejs.org/api/sfc-style.html) #602
* [x] [SFC Tooling](https://v3.ja.vuejs.org/api/sfc-tooling.html) #571
* [x] [Single File Components](https://v3.ja.vuejs.org/guide/single-file-component.html) #554 
* [x] #482

**Comment by kazupon** [comment]
@naokie 
>Vue and Web Components

これ、ちょっと自分翻訳やりたいと思います。 🙋‍♂️

**Comment by kazupon** [comment]
> > Vue and Web Components
> 
> これ、ちょっと自分翻訳やりたいと思います。 🙋‍♂️

もう、翻訳してしまいました。 😎 
https://github.com/vuejs-jp/ja.vuejs.org/pull/479

**Comment by naokie** [comment]
早い!!
レビュー、のちほどやっておきますね

**Comment by takumiz19** [comment]
@naokie 
> SFC Syntax Specification

これやりたいです！！

**Comment by naokie** [comment]
@takumiz19 よろしくお願いします！

**Comment by ryoAccount** [comment]
@naokie 
> Effect Scope API

こちらの翻訳を担当してもよろしいですか？

**Comment by naokie** [comment]
@ryoAccount 
ぜひ、担当してもらいたいです。よろしくお願いします！

**Comment by jay-es** [comment]
@naokie
> SFC `<script setup>`

こちら翻訳します！

**Comment by naokie** [comment]
@jay-es 
いつもありがとうございます！
実はやりかけのものがありまして #591 よければ、この続きからお願いします 🙏🏼

**Comment by jay-es** [comment]
@naokie おぉ、気づいてませんでした。
では、引き継がせていただきます！

**Comment by naokie** [comment]
3.2 のアップデート分、すべて翻訳完了しました 🎉 

協力いただいた @kazupon  @takumiz19 @ryoAccount @jay-es 
ありがとうございました 🙏🏼

**Comment by kazupon** [comment]
@naokie @takumiz19 @ryoAccount @jay-es
みなさん、翻訳ありがとうございました！

そして naokieさん、リードお疲れさまでした！
